# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTPExQGExHhSL79tqStfAL9ns9HJ4EEC
"""

import gradio as gr, numpy as np
from sudoku_solver import load_model, solve_with_steps, validate

model = load_model("sudoku_net.pt")

EXAMPLE = [
 [0,0,4,3,0,0,2,0,9],[0,0,5,0,0,9,0,0,1],[0,7,0,0,6,0,0,4,3],
 [0,0,6,0,0,2,0,8,7],[1,9,0,0,0,7,4,0,0],[0,5,0,0,8,3,0,0,0],
 [6,0,0,0,0,0,1,0,5],[0,0,3,5,0,8,6,9,0],[0,4,2,9,1,0,3,0,0]]

def to_grid(table):
    g = np.zeros((9, 9), dtype=np.int64)
    for r in range(9):
        for c in range(9):
            v = str(table[r][c]).strip()
            if v.isdigit() and 1 <= int(v) <= 9:
                g[r, c] = int(v)
    return g

def render(given, path, n):
    board, last = given.copy(), None
    for r, c, d in path[:n]:
        board[r, c], last = d, (r, c)
    rows = ""
    for r in range(9):
        cells = ""
        for c in range(9):
            v = board[r, c]
            s = "width:42px;height:42px;text-align:center;font-size:20px;border:1px solid #999;background:#fff;color:#000;"
            if c % 3 == 0: s += "border-left:3px solid #000;"
            if c == 8:     s += "border-right:3px solid #000;"
            if r % 3 == 0: s += "border-top:3px solid #000;"
            if r == 8:     s += "border-bottom:3px solid #000;"
            if given[r, c]: s += "font-weight:bold;"
            elif v:         s += "color:#1a73e8;"
            if last == (r, c): s += "background:#fff3b0;"
            cells += f"<td style='{s}'>{v if v else ''}</td>"
        rows += f"<tr>{cells}</tr>"
    return f"<table style='border-collapse:collapse;margin:auto;'>{rows}</table>"

def on_solve(table):
    given = to_grid(table)
    err = validate(given)
    if err:
        return render(given, [], 0), gr.update(maximum=1, value=0), err, {"given": given, "path": []}
    res = solve_with_steps(model, given)
    if res is None:
        return render(given, [], 0), gr.update(maximum=1, value=0), "Couldn't solve this one. Check the digits.", {"given": given, "path": []}
    path = res["path"]
    msg = f"Solved: {len(path)} cells filled, {res['tries'] - len(path)} guesses undone."
    return render(given, path, len(path)), gr.update(maximum=len(path), value=len(path)), msg, {"given": given, "path": path}

def on_slide(n, state):
    return render(state["given"], state["path"], int(n))

def load_example():
    return [[str(v) if v else "" for v in row] for row in EXAMPLE]

with gr.Blocks() as demo:
    gr.Markdown("## Neural Sudoku Solver\nType a puzzle (leave blanks empty), press Solve, then drag the slider to replay the moves. Bold = given, blue = filled by the model.")
    table = gr.Dataframe(value=[[""] * 9 for _ in range(9)], headers=[str(i) for i in range(1, 10)],
                         datatype="str", row_count=(9, "fixed"), col_count=(9, "fixed"),
                         type="array", interactive=True)
    with gr.Row():
        ex_btn = gr.Button("Load example")
        solve_btn = gr.Button("Solve", variant="primary")
    status = gr.Markdown()
    slider = gr.Slider(0, 81, value=0, step=1, label="Move number")
    board = gr.HTML()
    state = gr.State({"given": np.zeros((9, 9), dtype=np.int64), "path": []})

    ex_btn.click(load_example, outputs=table)
    solve_btn.click(on_solve, inputs=table, outputs=[board, slider, status, state])
    slider.change(on_slide, inputs=[slider, state], outputs=board)

demo.launch(share=True)